import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import ModalProvider from "@/providers/modal-provider";
import { ToasterProvider } from "@/providers/toast.provider";

import "./globals.css";
import prismadb from "@/lib/prismadb";
// import TempPage from "./temp-page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rare-Sight Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ToasterProvider />
          <ModalProvider />
          {/* <TempPage /> */}
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
